import 'package:flutter/material.dart';
import 'package:gharzo_project/model/payment_model/payment_dashboard_model.dart';
import 'package:intl/intl.dart';
// Ensure your model file is imported here
// import 'package:gharzo_project/models/payment_model.dart';

class PaymentDetailsScreen extends StatelessWidget {
  final RentPayment payment;

  const PaymentDetailsScreen({super.key, required this.payment});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF4F7FA),
      appBar: AppBar(
        title: Text(payment.paymentNumber,
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        centerTitle: true,
        elevation: 0,
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        actions: [
          IconButton(onPressed: () {}, icon: const Icon(Icons.share_outlined, size: 20)),
          const SizedBox(width: 8),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            _buildAmountHeader(),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildSectionTitle('Occupancy & Unit'),
                  _buildPropertyCard(),

                  _buildSectionTitle('Financial Summary'),
                  _buildBreakdownCard(),

                  _buildSectionTitle('Important Dates'),
                  _buildDateGrid(),

                  if (payment.timeline.isNotEmpty) ...[
                    _buildSectionTitle('Activity History'),
                    _buildTimeline(),
                  ],

                  if (payment.notes != null && payment.notes!.isNotEmpty) ...[
                    _buildSectionTitle('Admin Notes'),
                    _buildNoteCard(),
                  ],

                  const SizedBox(height: 32),
                  _buildPrimaryActions(),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAmountHeader() {
    return Container(
      width: double.infinity,
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(bottom: Radius.circular(32)),
      ),
      padding: const EdgeInsets.only(bottom: 32, top: 8),
      child: Column(
        children: [
          _statusBadge(payment.status),
          const SizedBox(height: 16),
          const Text('Final Payable Amount',
              style: TextStyle(color: Colors.grey, fontSize: 13, fontWeight: FontWeight.w500)),
          const SizedBox(height: 8),
          Text(
            '₹${payment.amounts.finalAmount.toStringAsFixed(0)}',
            style: const TextStyle(fontSize: 42, fontWeight: FontWeight.w900, color: Color(0xFF0D1724), letterSpacing: -1),
          ),
          if (payment.generatedBy != null)
            Padding(
              padding: const EdgeInsets.all(12),
              child: Text('Generated by ${payment.generatedBy!.name}',
                  style: TextStyle(color: Colors.grey[500], fontSize: 12)),
            ),
        ],
      ),
    );
  }

  Widget _buildPropertyCard() {
    return _customCard(
      child: Column(
        children: [
          _infoTile(Icons.apartment_rounded, 'Property', payment.property.title),
          const Divider(height: 24, thickness: 0.5),
          _infoTile(Icons.grid_view_rounded, 'Unit Number', 'Room ${payment.room.roomNumber}'),
          const Divider(height: 24, thickness: 0.5),
          _infoTile(Icons.person_pin_rounded, 'Tenant', payment.tenant.name, sub: payment.tenant.phone),
        ],
      ),
    );
  }

  Widget _buildBreakdownCard() {
    final amt = payment.amounts;
    return _customCard(
      child: Column(
        children: [
          _amountRow('Monthly Rent', amt.monthlyRent),
          _amountRow('Maintenance', amt.maintenanceCharges),
          if (amt.waterCharges > 0) _amountRow('Water Charges', amt.waterCharges),
          if (amt.electricityCharges > 0) _amountRow('Electricity', amt.electricityCharges),
          if (amt.lateFee > 0)
            _amountRow('Late Fee (${payment.lateFeeCalculation.daysOverdue} days)', amt.lateFee, color: Colors.red),
          if (amt.discount > 0)
            _amountRow('Discount', -amt.discount, color: Colors.green),
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 12),
            child: Divider(thickness: 1),
          ),
          _amountRow('Total Amount', amt.finalAmount, isBold: true, fontSize: 17),
        ],
      ),
    );
  }

  Widget _buildDateGrid() {
    return _customCard(
      child: GridView.count(
        shrinkWrap: true,
        physics: const NeverScrollableScrollPhysics(),
        crossAxisCount: 2,
        childAspectRatio: 2.5,
        children: [
          _dateItem('Billing Period', '${_month(payment.billingPeriod.month)} ${payment.billingPeriod.year}'),
          _dateItem('Due Date', _format(payment.dates.dueDate)),
          _dateItem('Generated On', _format(payment.dates.generatedDate)),
          _dateItem('Grace Period', _format(payment.dates.gracePeriodEndDate)),
        ],
      ),
    );
  }

  Widget _buildTimeline() {
    return _customCard(
      child: Column(
        children: payment.timeline.map((entry) {
          return Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Column(
                  children: [
                    const Icon(Icons.check_circle, size: 18, color: Colors.blueAccent),
                    if (entry != payment.timeline.last)
                      Container(width: 1.5, height: 35, color: Colors.blueAccent.withOpacity(0.2)),
                  ],
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(entry.action, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                      Text(_format(entry.timestamp, showTime: true),
                          style: TextStyle(color: Colors.grey[600], fontSize: 11)),
                      if (entry.notes.isNotEmpty)
                        Text(entry.notes, style: const TextStyle(fontSize: 12, color: Colors.black87)),
                    ],
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildNoteCard() {
    return _customCard(
      child: Text(payment.notes!, style: const TextStyle(fontSize: 13, height: 1.5, color: Colors.black87)),
    );
  }

  /// Helper UI Builders
  Widget _customCard({required Widget child}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(color: Colors.black.withOpacity(0.02), blurRadius: 10, offset: const Offset(0, 4))
        ],
      ),
      child: child,
    );
  }

  Widget _infoTile(IconData icon, String label, String value, {String? sub}) {
    return Row(
      children: [
        Container(
          padding: const EdgeInsets.all(8),
          decoration: BoxDecoration(color: const Color(0xFFF0F4FF), borderRadius: BorderRadius.circular(10)),
          child: Icon(icon, color: const Color(0xFF3F51B5), size: 20),
        ),
        const SizedBox(width: 12),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label, style: TextStyle(color: Colors.grey[500], fontSize: 11, fontWeight: FontWeight.w600)),
            Text(value, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
            if (sub != null) Text(sub, style: TextStyle(color: Colors.grey[600], fontSize: 12)),
          ],
        ),
      ],
    );
  }

  Widget _amountRow(String title, num val, {bool isBold = false, Color? color, double fontSize = 14}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(title, style: TextStyle(fontSize: fontSize, fontWeight: isBold ? FontWeight.bold : FontWeight.w500, color: Colors.grey[700])),
          Text('${val < 0 ? "-" : ""}₹${val.abs().toStringAsFixed(0)}',
              style: TextStyle(fontSize: fontSize, fontWeight: isBold ? FontWeight.bold : FontWeight.w700, color: color ?? Colors.black)),
        ],
      ),
    );
  }

  Widget _dateItem(String label, String val) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text(label, style: TextStyle(color: Colors.grey[500], fontSize: 10, fontWeight: FontWeight.bold)),
        Text(val, style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13)),
      ],
    );
  }

  Widget _statusBadge(String status) {
    Color color = status == 'Paid' ? Colors.green : (status == 'Pending' ? Colors.orange : Colors.red);
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
      decoration: BoxDecoration(color: color.withOpacity(0.1), borderRadius: BorderRadius.circular(30)),
      child: Text(status.toUpperCase(),
          style: TextStyle(color: color, fontSize: 10, fontWeight: FontWeight.w900, letterSpacing: 1)),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(left: 4, top: 20, bottom: 10),
      child: Text(title.toUpperCase(),
          style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w800, color: Color(0xFF94A3B8), letterSpacing: 1.5)),
    );
  }

  Widget _buildPrimaryActions() {
    return Row(
      children: [
        Expanded(
          child: ElevatedButton(
            onPressed: () {},
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF1A237E),
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 18),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
              elevation: 0,
            ),
            child: const Text('Record Payment', style: TextStyle(fontWeight: FontWeight.bold)),
          ),
        ),
      ],
    );
  }

  String _format(DateTime date, {bool showTime = false}) =>
      DateFormat(showTime ? 'dd MMM yyyy, hh:mm a' : 'dd MMM, yyyy').format(date);

  String _month(int m) => DateFormat('MMMM').format(DateTime(2026, m));
}