// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXR_Ff6HAxDMlHuxoy5aB2kseGxFj14g',
    appId: '1:4398272942:web:ccdec2e249d32220b4783f',
    messagingSenderId: '4398272942',
    projectId: 'gharzo-d5832',
    authDomain: 'gharzo-d5832.firebaseapp.com',
    storageBucket: 'gharzo-d5832.firebasestorage.app',
    measurementId: 'G-NK27CGMLKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYeEG9aT2yW_doR8F9aSzOKX0aN8LBD4',
    appId: '1:4398272942:android:e9aeb263d2748401b4783f',
    messagingSenderId: '4398272942',
    projectId: 'gharzo-d5832',
    storageBucket: 'gharzo-d5832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnAPTacz5gG2dt2M2gNddxX1L8HQg-Ci0',
    appId: '1:4398272942:ios:a118dfe547cff093b4783f',
    messagingSenderId: '4398272942',
    projectId: 'gharzo-d5832',
    storageBucket: 'gharzo-d5832.firebasestorage.app',
    iosBundleId: 'com.example.gharzoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnAPTacz5gG2dt2M2gNddxX1L8HQg-Ci0',
    appId: '1:4398272942:ios:a118dfe547cff093b4783f',
    messagingSenderId: '4398272942',
    projectId: 'gharzo-d5832',
    storageBucket: 'gharzo-d5832.firebasestorage.app',
    iosBundleId: 'com.example.gharzoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMXR_Ff6HAxDMlHuxoy5aB2kseGxFj14g',
    appId: '1:4398272942:web:9838cb16c064fa63b4783f',
    messagingSenderId: '4398272942',
    projectId: 'gharzo-d5832',
    authDomain: 'gharzo-d5832.firebaseapp.com',
    storageBucket: 'gharzo-d5832.firebasestorage.app',
    measurementId: 'G-4BJRQWGYS0',
  );
}
